exports. carModelList = [
    'Mehran VX Euro II Limited Edition',
    'Mehran VX Euro II',
    'Mehran VXR Euro II',
    'Mehran VX',
    'Mehran VXR',
    'Mehran',
    'Alto VXL',
    'Alto VXR',
    'Alto VXL AGS',
    'Alto VXR AGS',
    'Alto E',
    'Alto ECO-L',
    'Alto ECO-S',
    'Alto F',
    'Alto G',
    'Alto X',
    'Alto TURBO RS',
    'Alto L',
    'Alto G',
    'Alto G4',
    'Alto works edition',
    'Alto',
    'Wagon R Hybrid FX',
    'Wagon R VXL',
    'Wagon R FX',
    'Wagon R VXR',
    'Wagon R AGS',
    'Wagon R',
    'Swift DLX 1.3',
    'Swift DLX 1.3 Navigation',
    'Swift DLX Automatic 1.3',
    'Swift DLX Automatic 1.3 Navigation',
    'Swift DX 1.3',
    'Swift',
    'Cultus AGS',
    'Cultus EURO II',
    'Cultus VXL',
    'Cultus VXLi',
    'Cultus VXR',
    'Cultus VXRi',
    'Cultus'
]

exports. cities = [
    'Islamabad',
    'Lahore',
    'Karachi',
    'Rawalpindi'
]

exports. fileName = 'Car Details.csv'